### ISSUE TITLE
Unable to connect with grpc client 

### ISSUE THREAD

**Issue by surajchhetry** [projectcontour/contour#3427]
Hi, 
 I am not able to connect with the grpc server getting a grpc client connection error. Can anybody help me with this issue?
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
    name: test-service
    namespace: default
  spec:
    tcpproxy:
      services:
        - name: test-backend-service
          port: 8080
          protocol: h2
    virtualhost:
      fqdn: test-service.example.com
      tls:
        secretName: test-secretName
```
```
Mar 02, 2021 4:28:36 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 1603010077010000730303ac3620a4bf5d7acdee73b1b15d
at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108)
at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:306)
at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:853)
```

```
apiVersion: v1
kind: Service
metadata:
  name: test-backend-service
  labels:
    app: test-backend-service
  annotations:
    projectcontour.io/upstream-protocol.h2: "8080"
spec:
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: test-backend-service
  type: ClusterIP
  sessionAffinity: None
```

**Comment by stevesloka** [comment]
Does your backend support TLS @surajchhetry? Using the `h2` means it will route over TLS. If your backend isn't then you should use `h2c`. 

Also you don't need the `protocol` field as well as the annotation on the service, you can pick one or the other (but the `protocol` takes precedence).

**Comment by surajchhetry** [comment]
Thank you @stevesloka,  after removing annotation from service and converting protocol to h2c, it is working now.
