### ISSUE TITLE
in-cluster smoke test regularly timing out

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#6125]
The in-cluster smoke test, both the standard one and the IPv6 variant, seem to be timing out regularly, however the test is still passing. See e.g. https://github.com/skriss/contour/actions/runs/7672865296/job/20914512289 and https://github.com/skriss/contour/actions/runs/7672865296/job/20914511926.

**Comment by sunjayBhatia** [comment]
I think that might be the newer behavior of ginkgo where it shows you progress for slow tests since we pass `-poll-progress-after=120s`

**Comment by sunjayBhatia** [comment]
Assuming we're talking about this output:

```
------------------------------
  Automatically polling progress:
    Incluster with namespace: smoke-test simple smoke test (Spec Runtime: 2m25.947s)
      /home/runner/work/contour/contour/test/e2e/incluster/smoke_test.go:29
      In [It] (Node Runtime: 2m0.001s)
        /home/runner/work/contour/contour/test/e2e/incluster/smoke_test.go:29

      Spec Goroutine
      goroutine 657 [select]
        k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext({0x1af96b0, 0xc0006bdc00}, {0x1af0b70?, 0xc000305780}, 0x1, 0x0, 0x30?)
          /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.1/pkg/util/wait/loop.go:66
        k8s.io/apimachinery/pkg/util/wait.PollUntilContextTimeout({0x1af9560?, 0x27d1240?}, 0x3b9aca00, 0xc000a33d01?, 0x20?, 0x1516fbd?)
          /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.1/pkg/util/wait/poll.go:48
      > github.com/projectcontour/contour/test/e2e.(*HTTP).requestUntil(0x0?, 0x0?, 0x0?)
          /home/runner/work/contour/contour/test/e2e/http.go:291
            | var res *HTTPResponse
            | 
            > if err := wait.PollUntilContextTimeout(context.Background(), h.RetryInterval, h.RetryTimeout, true, func(ctx context.Context) (bool, error) {
            | 	r, err := makeRequest()
            | 	if err != nil {
      > github.com/projectcontour/contour/test/e2e.(*HTTP).RequestUntil(0xc0006b0060, 0xc000a33ef0)
          /home/runner/work/contour/contour/test/e2e/http.go:134
            | 	}
            | 
            > 	return h.requestUntil(makeRequest, opts.Condition)
            | }
            | 
      > github.com/projectcontour/contour/test/e2e/incluster.testSimpleSmoke.func1()
          /home/runner/work/contour/contour/test/e2e/incluster/smoke_test.go:61
            | f.CreateHTTPProxyAndWaitFor(p, e2e.HTTPProxyValid)
            | 
            > res, ok := f.HTTP.RequestUntil(&e2e.HTTPRequestOpts{
            | 	Host:      p.Spec.VirtualHost.Fqdn,
            | 	Condition: e2e.HasStatusCode(200),
        github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x9e[248](https://github.com/skriss/contour/actions/runs/7672865296/job/20914511926#step:7:249)8, 0xc00032db00})
          /home/runner/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.15.0/internal/node.go:463
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
          /home/runner/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.15.0/internal/suite.go:889
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 9
          /home/runner/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.15.0/internal/suite.go:876
  ------------------------------
•••••• SUCCESS! 6m41.529997437s PASS
```

**Comment by skriss** [comment]
Ah, good call, saw orange while looking at other things and did not read carefully.
